name: app

services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_DEFAULT_EMAIL: test@test.de
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  pg:
    image: postgres
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: d_app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
